services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: DB1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist PostgreSQL data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # Persist pgAdmin settings and registered servers
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local  # Volume for PostgreSQL data persistence
  pgadmin_data:
    driver: local  # Volume for pgAdmin data persistence (settings, registered servers)

networks:
  app-network:
    driver: bridge
